import subprocess
from api_calls.openai_api import OpenAIAPI

def find_pip_installed_packages():
    result = subprocess.run(["pip", "list"], capture_output=True, text=True)
    return result.stdout

libraries = find_pip_installed_packages()

class IdeaGenerator:
    def __init__(self):
        self.create = OpenAIAPI()

    def generate_idea(self, web_research_results):
        career = self.create.api_calls(
            "Create a career persona for an AI developer specializing in Python. This career must be focused on idea generation of projects that leverage AI technologies to create innovative solutions with significant market potential.",
            "You are a career specialist providing guidance to an entrepreneurial Python developer specializing in AI."
        )

        try:
            system_message = f"""
            Persona: {career}

            As an idea generation specialist, your task is to generate a groundbreaking project idea for an entrepreneurial Python developer specializing in AI. The project should meet the following criteria:

            1. Leverage AI technologies, particularly neural networks, to create innovative solutions in areas such as video processing, image generation, or content creation.
            2. Have a strong potential for commercialization and substantial financial returns.
            3. Showcase the capabilities of Python and AI in solving real-world problems or enhancing existing products/services.
            4. Be feasible to implement within a single run or with minimal refinements from the development team.
            5. Have a clear path to profitability and a well-defined target market.
            6. Be achievable using the existing Python libraries and AI frameworks available to the developer.
            7. Have a positive impact on society and contribute to the advancement of AI technologies.
            8. All programs must properly profit from initial running and start based on the initial run. This means all must directly profit from your ideas not indirectly through sales or purchasing other things.
            9. Consider the following web research results: {web_research_results}

            Generate an idea that is creative, plausible (within a single Python script able to be generated by AI chatbots), and has the potential to revolutionize the industry while being practical to implement. Provide a clear and concise description of the project idea, highlighting its key features, benefits, and potential profitability.
            Don't put placeholders such as 'pass' in your code. Make sure to remove all comments and placeholders.
            Never use models that don't exist or extensive libraries that may be updated.
            """

            user_message = "Please generate a feasible and profitable project idea (able to be coded by AI in a single file Python script) that can be implemented within a single run or with minimal refinements from the development team."

            idea = self.create.api_calls(user_message, system_message)
            return idea

        except Exception as e:
            return ""